EJERCICIO 1:

SELECT PER.* FROM casting CAST INNER JOIN perfil_casting PC ON CAST.CODIGO = PC.CODIGO_CASTING 
JOIN evaluacion EVA ON PC.CODIGO_PERFIL_CASTING = EVA.CODIGO_PERFIL_CASTING JOIN 
candidato CAN ON EVA.CODIGO_CANDIDATO = CAN.CODIGO JOIN perfil PER ON CAN.CODIGO_PERFIL = PER.CODIGO WHERE CAST.CODIGO = 1;

CUAL ES EL PERFIL DE LOS CANDIDATOS QUE REALIZARON LA EVALUACION PARA EL CASTING 1

JOIN ES LO MISMO QUE INNER JOIN, ES EL ENCARGADO DE METER UNA NUEVA TABLA 
ON ES EL ENCARGADO DE CUMPLIR EL ENTRELAZAMIENTO ENTRE TABLAS CON VALORES IGUALES
EL WHERE ES EL CONDICIONAL QUE EN ESTE CASO LLAMA A LAS PERSONAS DEL CASTING 1

EJERCICIO 2:

MOSTRAR QUE PRODUCTOS HAN SALIDO DE LOS QUE TRAJO EL CONDUCTOR CON CODIGO 6:

SELECT PER.* FROM casting CAST INNER JOIN perfil_casting PC ON CAST.CODIGO = PC.CODIGO_CASTING 
JOIN evaluacion EVA ON PC.CODIGO_PERFIL_CASTING = EVA.CODIGO_PERFIL_CASTING JOIN 
candidato CAN ON EVA.CODIGO_CANDIDATO = CAN.CODIGO JOIN perfil PER ON CAN.CODIGO_PERFIL = PER.CODIGO WHERE CAST.CODIGO = 1;


