--CREACION TABLAS--

--TABLA GUSTOS--
CREATE TABLE `help me`.`gustos` (`ID_GUSTOS` INT(10) NOT NULL , `TITULO` VARCHAR(20) NOT NULL , `DESCRIPCION` VARCHAR(50) NOT NULL 
, PRIMARY KEY (`ID_GUSTOS`)) 

--TABLA MARCOS--
CREATE TABLE `help me`.`marcos` (`ID_MARCO` INT(10) NOT NULL , `NOMBRE` VARCHAR(20) NOT NULL , `PARTICIPACIONES` VARCHAR(50) NOT NULL 
, PRIMARY KEY (`ID_MARCO`)) 

--TABLA PAISES--
CREATE TABLE `help me`.`paises` (`ID_PAIS` INT(10) NOT NULL , `NOMBRE` VARCHAR(20) NOT NULL , 
PRIMARY KEY (`ID_PAIS`)) 

--TABLA MULTIMEDIA--
CREATE TABLE `help me`.`multimedia` (`ID_MULTIMEDIA` INT(10) NOT NULL , `ENLACE` VARCHAR(500) NOT NULL , 
PRIMARY KEY (`ID_MULTIMEDIA`)) 

--TABLA GUSTOS USUARIOS--
CREATE TABLE `help me`.`gustos_usuario` (`ID_GUSTOS_USUARIO` INT(10) NOT NULL , `USUARIO` VARCHAR(100) NOT NULL , 
`GUSTOS` INT(10) NOT NULL , PRIMARY KEY (`ID_GUSTOS_USUARIO`),
FOREIGN KEY (USUARIO) REFERENCES usuarios (CORREO_U), FOREIGN KEY (GUSTOS) REFERENCES gustos (ID_GUSTOS));

--TABLA USUARIOS--
CREATE TABLE `help me`.`usuarios` (`CORREO_USUARIO` VARCHAR(100) NOT NULL , `PASWORD` VARCHAR(100) NOT NULL , 
`NOMBRE` VARCHAR(50) NOT NULL , `DESCRIPCION` TEXT NOT NULL , `EDAD` INT(3) NOT NULL , `FIJADOS` VARCHAR(100) NOT NULL , 
`FOTO_PERFIL` INT(10) NOT NULL , `GUSTOS` INT(10) NOT NULL , `MARCO` INT(10) NOT NULL , `RESIDENCIA` INT(10) NOT NULL , 
PRIMARY KEY (`CORREO_USUARIO`), FOREIGN KEY (FOTO_PERFIL) REFERENCES multimedia (id_multimedia), 
FOREIGN KEY (GUSTOS) REFERENCES gustos_usuario (ID_GUSTOS_USUARIO), FOREIGN KEY (MARCO) REFERENCES marcos (ID_MARCO), 
FOREIGN KEY (RESIDENCIA) REFERENCES paises (ID_PAIS));

--TIPO PUBLICACION--
CREATE TABLE `help me`.`tipo_publicacion` (`ID_TIPO_PUBLICACION` INT(10) NOT NULL , `DESCRIPCION` VARCHAR(100) NOT NULL ,
PRIMARY KEY (`ID_TIPO_PUBLICACION`))

--MULTIMEDIA PUBLICACION--
CREATE TABLE `help me`.`multimedia_publicacion` (`ID_MULTIMEDIA_PUBLICACION` INT(10) NOT NULL , `MULTIMEDIA` VARCHAR(500) NOT NULL ,
`PUBLICACION` INT(10) NOT NULL , PRIMARY KEY (`ID_MULTIMEDIA_PUBLICACION`), FOREIGN KEY (MULTIMEDIA) REFERENCES multimedia (ID_MULTIMEDIA),
FOREIGN KEY (PUBLICACION) REFERENCES publicaciones (ID_PUBLICACION)) 

--PUBLICACIONES--
CREATE TABLE `help me`.`publicaciones` (`ID_PUBLICACION` INT(10) NOT NULL , `TITULO` VARCHAR(20) NOT NULL , 
`FECHA` DATE NOT NULL , `DESCRIPCION` VARCHAR(500) NOT NULL , `PADRE` INT(10) NOT NULL , `TIPO` INT(10) NOT NULL ,
`AUTOR` VARCHAR(500) NOT NULL , `MULTIMEDIA` INT(10) NOT NULL , PRIMARY KEY (`ID_PUBLICACION`), 
FOREIGN KEY (PADRE) REFERENCES publicaciones (ID_PUBLICACION), FOREIGN KEY (TIPO) REFERENCES tipo_publicacion (ID_TIPO_PUBLICACION),
FOREIGN KEY (AUTOR) REFERENCES usuarios (CORREO_U) FOREIGN KEY (MULTIMEDIA) REFERENCES multimedia_publicacion (ID_MULTIMEDIA_PUBLICACION)) 

--ENCUESTA--
CREATE TABLE `help me`.`encuesta` (`ID_ENCUESTA` INT(10) NOT NULL , `OP1` VARCHAR(500) NOT NULL , `OP2` VARCHAR(500) NOT NULL ,
`OP3` VARCHAR(500) NOT NULL , `OP4` VARCHAR(500) NOT NULL , `PUBLICACION` INT(10) NOT NULL ), FOREIGN KEY (PUBLICACION) REFERENCES publicaciones (ID_PUBLICACION);

--RESPUESTA ENCUESTA--
CREATE TABLE `help me`.`respuesta_encuesta` (`ID_RESPUESTA` INT(10) NOT NULL , `RESPUESTA` VARCHAR(500) NOT NULL , 
`PUBLICACION` INT(10) NOT NULL , `USUARIO` VARCHAR(500) NOT NULL , PRIMARY KEY (`ID_RESPUESTA`), 
FOREIGN KEY (PUBLICACION) REFERENCES publicaciones (ID_PUBLICACION), FOREIGN KEY (USUARIO) REFERENCES usuarios (CORREO_U));
